### ISSUE TITLE
Plugin provided an invalid property of "default"

### ISSUE THREAD

**Issue by zaggino** [loganfsmyth/babel-plugin-transform-builtin-extend#1]
Tried using the plugin here: https://github.com/pureprofile-warp/babel-preset-pp-node4/blob/master/index.js but on start I get an error:

```
C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\plugin.js:125
      throw new Error(messages.get("pluginInvalidProperty", loc, i, key));
      ^

Error: Plugin 0 specified in "C:\\dev\\pureprofile\\ah-api-web\\node_modules\\babel-preset-pp-node4\\index.js" provided an invalid property of "default"
    at Plugin.init (C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\plugin.js:125:13)
    at Function.normalisePlugin (C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:167:12)
    at C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:197:30
    at Array.map (native)
    at Function.normalisePlugins (C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:173:20)
    at OptionManager.mergeOptions (C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:271:36)
    at OptionManager.mergePresets (C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:325:16)
    at OptionManager.mergeOptions (C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:287:12)
    at OptionManager.addConfig (C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:221:10)
    at OptionManager.findConfigs (C:\dev\pureprofile\ah-api-web\node_modules\babel-core\lib\transformation\file\options\option-manager.js:364:16)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by loganfsmyth** [comment]
Sorry, did you ever figure out the cause of this? As long as you are on a recent version of Babel, I wouldn't expect this behavior.

**Comment by kt3k** [comment]
Because this plugin exports only `exports.default` and doesn't export `module.exports`, maybe you need to put `require("babel-plugin-transform-builtin-extend").default` instead of `require("babel-plugin-transform-builtin-extend")`.

I saw a similar error when I was creating [this preset](https://github.com/kt3k/babel-preset-es2015-and-decorators/blob/master/index.js).
Babel's official transforms still export both `module.exports` and `module.exports.default` and that's why you don't need to put `.default` after `require(...)` when requiring them.

**Comment by zaggino** [comment]
That indeed worked: https://github.com/pureprofile-warp/babel-preset-pp-node4/commit/d6c0d193157d92a49a6296506aab05231cfbcb6b
Thanks @kt3k

**Comment by kt3k** [comment]
:smile: :+1:

**Comment by yvele** [comment]
@kt3k I ran in the same issue, thank you so much for the `.default`workarround 👍
