### ISSUE TITLE
When trying to run tests

### ISSUE THREAD

**Issue by akond** [loganfsmyth/babel-plugin-transform-builtin-extend#5]
```
 >
 > npm test

> babel-plugin-transform-builtin-extend@1.1.0 test /mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend
> babel-node node_modules/.bin/_mocha --recursive test

/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "../" specified in "/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/test/approximate/.babelrc" at 0, attempted to resolve relative to "/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/test/approximate"
    at /mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-register/lib/node.js:103:45)
    at loader (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at /mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-cli/lib/_babel-node.js:159:24
    at Object.<anonymous> (/mnt/sda5/Resources/temp/babel-plugin-transform-builtin-extend/node_modules/babel-cli/lib/_babel-node.js:160:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
npm ERR! Test failed.  See above for more details.

```

**Comment by oravecz** [comment]
I think the devs put the tests in subdirectories and forgot to commit the new .babelrc files. Change the entry in the .babelrc files from '../' to '../../'
